version: '3'
services:
  jenkins:
    image: alekseysamoylov/nastushenka_jenkins:latest
    ports:
    - '3001:8080'
    - '3443:8443'
    environment:
    - JENKINS_USERNAME=user
    - JENKINS_PASSWORD=secret
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
